# Configurations
title:            Algebra Linear
longtitle:        Algebra Linear
author:           Rafael Rangel 
email:            rafaelj492@gmail.com
description: >
  A álgebra linear é a espinha dorsal do aprendizado de máquina, oferecendo as ferramentas essenciais para manipulação de dados e desenvolvimento de algoritmos eficientes, desde a representação de conjuntos de dados até a otimização de modelos complexos.

version:          1.0
gitbook_version:  3.2.3

url:              'https://rajora0.github.io'
baseurl:          '/algebra-linear'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/algebra_linear

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
